#ifndef JINPA_AUTO_TRADE_TYPES_MQH
#define JINPA_AUTO_TRADE_TYPES_MQH

enum JINPA_AUTO_SETUP_MODE
{
    AUTO_PULLBACK = 0,
    AUTO_BREAKOUT = 1,
    AUTO_RANGE_REVERSAL = 2,
    AUTO_ALL = 3
};

#endif // JINPA_AUTO_TRADE_TYPES_MQH
